### ISSUE TITLE
Calling delay() from within the constructor crashes Arduino Pro Mini

### ISSUE THREAD

**Issue by flurl** [fablab-bayreuth/WTV020SD16P#1]
Using your library i noticed, that my sketch did not run, because in the constructor, there's a call to `reset()` which uses the `delay() `function.
Calling` delay()` from within the constructor of a global object is disadvised, as `delay()` will never return.

See https://github.com/arduino/Arduino/issues/129

I replaced the `delay()` calls in `reset()` with calls to `delayMicros()` wich made it work.

**Comment by thirsch** [comment]
Thank you for your feedback. As I don't have any running sketch available at the moment, I changed it directly in the code. Do you still have your sketch available and can test the new version?
